server:
  port: 8080

spring:
  application:
    name: security
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      format-sql: true
      dialect: .org.hibernate.dialect.MySQL8Dialect
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
    open-in-view: false
  #    defer-datasource-initialization: true

  datasource:
    url: jdbc:mysql://localhost:3308/spring
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root1234!!
